drop table employees
/*CREATE DATABASE dbEmployee
ON PRIMARY
(
	NAME=dbEmployee_DAT,
	FILENAME='D:\56110177\dbEmployee.mdf',
	SIZE=4,
	MAXSIZE=20,
	FILEGROWTH=1
)
LOG ON
(
	NAME=dbEmployee_LOG,
	FILENAME='D:\56110177\dbEmployee.ldf',
	SIZE=2,
	MAXSIZE=5,
	FILEGROWTH=1
)	*/

CREATE TABLE EMPLOYEE
(
	Empno CHAR (4) NOT NULL,
	Empname VARCHAR(20) NOT NULL,
	Address VARCHAR (20) NOT NULL,
	Hiredate DATETIME NOT NULL,
	Position VARCHAR(15) NOT NULL,
	Salary INT NOT NULL,
	Skill VARCHAR(50),
		CONSTRAINT EMPLOYEE_Empno_PK PRIMARY KEY
	(Empno) ,
		CONSTRAINT EMPLOYEE_Empno_UK UNIQUE
	(Empname)		
)
CREATE TABLE DEPARMENT
(
	Depno CHAR(2) NOT NULL,
	Depname VARCHAR(15) NOT NULL,
	Location VARCHAR(15) NOT NULL,
	CONSTRAINT DEPARMENT_Depno_PK PRIMARY KEY (Depno)
)
CREATE TABLE CUSTOMER
(
	Custno CHAR(4) NOT NULL,
	Custname VARCHAR(20)NOT NULL,
	Address	VARCHAR(30)NOT NULL,
	Telno CHAR(13)NOT NULL,
	CONSTRAINT CUSTOMER_Custno_PK PRIMARY KEY (Custno)
)

CREATE TABLE ORDERS
(
	Orderno CHAR(4) NOT NULL,
	orderdata DATETIME NOT NULL,
	CONSTRAINT ORDERS_Orderno_PK PRIMARY KEY (Orderno)
)


CREATE TABLE PRODUCT
(
	Prodno CHAR(2) NOT NULL,
	Proname INT NOT NULL,
	Cost INT NOT NULL,
	Balance INT NOT NULL,
	CONSTRAINT PRODUCT_Prodno_PK PRIMARY KEY (ProdNo)
	
)
CREATE TABLE ORDERITEM
(
	Orderno CHAR (4) NOT NULL,
	Prodno CHAR (2) NOT NULL,
	Orderqty INT NOT NULL,
	Orderprice INT NOT NULL,
	
	CONSTRAINT ORDERITEM_Orderno_PK PRIMARY KEY (Orderno)
)
CREATE TABLE SUPPLIER
(
	Sno CHAR(2) NOT NULL,
	Sname VARCHAR(20) NOT NULL,
	Address VARCHAR(13) NOT NULL,
	telno CHAR(13) NOT NULL,
	CONSTRAINT SUPPLIER_Sno_PK PRIMARY KEY (Sno)
)
CREATE TABLE DEPENDENT
(
	Empno CHAR(4) NOT NULL,
	Dependent_name VARCHAR(20) NOT NULL,
	relation VARCHAR(15) NOT NULL,
	CONSTRAINT DEPENDENT_Dependent_name_PK PRIMARY KEY (Dependent_name) 
)

CREATE TABLE CUSTOMER_TYPE
(
	Cust_type CHAR(5) NOT NULL,
	Discount_rate INT NOT NULL,
	
	CONSTRAINT CUSTOMER_TYPE_Cust_type_PK PRIMARY KEY (Cust_type) 
)

CREATE TABLE jobs
(
	job_id VARCHAR(10) NOT NULL,
	description VARCHAR(255) NOT NULL,
	
	CONSTRAINT JOBS_ID_TYPE_PK PRIMARY KEY(job_id)
)
CREATE TABLE employees
(	
	employee_id VARCHAR(10) NOT NULL,
	name VARCHAR(255) NOT NULL,
	department_id VARCHAR(10) NOT NULL,
	job_id VARCHAR(10) NOT NULL,
	salary DECIMAL(7,2) NOT NULL,
	CONSTRAINT EMPLOYEE_ID_TYPE_PK PRIMARY KEY(employee_id)
)
CREATE TABLE deparments
(
	deparment_id VARCHAR(10) NOT NULL,
	name VARCHAR(255) NOT NULL,
	 CONSTRAINT DEOARMENT_ID_TYPE_PK PRIMARY KEY (deparment_id)
)